-- Distribution Tables Schema
-- Generated by taxprep-data-extraction

BEGIN;

-- ============================================================================
-- PUMS DISTRIBUTION TABLES (9 tables)
-- ============================================================================
-- Created by extract_pums_distributions.py
--
-- Tables:
--   1. household_patterns
--   2. employment_by_age
--   3. children_by_parent_age
--   4. child_age_distributions
--   5. social_security
--   6. retirement_income
--   7. interest_and_dividend_income
--   8. property_taxes
--   9. mortgage_interest
--
-- See output/pums_distributions_[STATE]_[YEAR].sql for complete schema


-- ============================================================================
-- BLS DISTRIBUTION TABLES (1 table)
-- ============================================================================
-- Created by extract_bls_distributions.py
--
-- Tables:
--   1. bls_occupation_wages
--
-- See output/bls_occupation_wages_[STATE]_[YEAR].sql for complete schema


-- ============================================================================
-- DERIVED DISTRIBUTION TABLES (3 tables)
-- ============================================================================
-- Created by extract_derived_distributions.py
--
-- Tables:
--   1. education_occupation_probabilities
--   2. age_income_adjustments
--   3. occupation_self_employment_probability
--
-- See output/derived_probabilities_[STATE]_[YEAR].sql for complete schema


-- ============================================================================
-- NOTES
-- ============================================================================
-- 
-- This file documents the schema structure but does not create tables.
-- Table creation happens when importing the generated SQL files.
--
-- To import all tables:
--   ./database/import_all.sh [STATE_CODE]
--
-- Example:
--   ./database/import_all.sh HI
--

COMMIT;
